import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import path from "node:path";
export const root = fileURLToPath(new URL("../../../", import.meta.url));
const read = (p) =>
  readFileSync(path.join(root, p), "utf8").replace(/\r\n/g, "\n");
const shader = (name) => read(`packages/blackhole/shaders/${name}.glsl`);
const local = (name) => read(`integrations/ghostty/src/${name}.glsl`);
const hash = (p) =>
  createHash("sha256")
    .update(p.endsWith(".woff2") ? readFileSync(path.join(root, p)) : read(p))
    .digest("hex");
function replaceOnce(source, from, to) {
  if (!source.includes(from))
    throw Error(`Canonical shader interface changed: ${from}`);
  return source.replace(from, to);
}
export function generate() {
  for (const [p, expected] of Object.entries(
    JSON.parse(read("integrations/ghostty/src/atlas-inputs.json")),
  ))
    if (hash(p) !== expected)
      throw Error(
        `Glyph/camera inputs changed: ${p}; recapture and seal atlas before generating`,
      );
  const atlas = JSON.parse(read("integrations/ghostty/src/glyph-atlas.json"));
  const inputs = ["buffer-a", "image", "ascii-analysis", "ascii"].map(
    (n) => `packages/blackhole/shaders/${n}.glsl`,
  );
  inputs.push(
    "packages/blackhole/routes.json",
    "packages/blackhole/fonts/DepartureMono-Regular.woff2",
    "packages/blackhole/src/components/BlackHoleCore.ts",
    "packages/blackhole/src/lib/ascii-analysis.ts",
    "integrations/ghostty/src/glyph-atlas.json",
  );
  const fingerprint = inputs.map((p) => `// ${p}: ${hash(p)}`).join("\n");
  const banner = `// GENERATED by integrations/ghostty/scripts/generate.mjs. Do not edit shader bodies.\n// GPL-3.0-only. Canonical NPGS-derived Kerr-Newman renderer; see NOTICE.md.\n// Departure Mono raster: SIL OFL 1.1; see DepartureMono-OFL-1.1.txt.\n${fingerprint}\n`;
  let core = shader("buffer-a");
  const marker = core.indexOf("// SECTION 9: mainImage");
  if (marker < 0) throw Error("Missing core boundary");
  const history =
    /    vec4 PrevColor[\s\S]*FragColor = \(iBlendWeight\) \* FinalColor \+ \(1.0 - iBlendWeight\) \* PrevColor;/;
  if (!history.test(core)) throw Error("Canonical history interface changed");
  core = replaceOnce(core, "void mainImage(", "void bhCanonicalTrace(")
    .replace(history, "    FragColor = FinalColor;")
    .replaceAll("iResolution.xy", "vec2(bhSourceSize())")
    .replaceAll("iResolution.y", "float(bhSourceSize().y)")
    .replace(/^#define iQuality\s+1\.0.*$/m, "#define iQuality uQuality")
    .replace(/^#define iPrepass\s+0.*$/m, "#define iPrepass 1");
  const image = shader("image");
  const display = image.slice(
    image.indexOf("vec3 DisplayColor("),
    image.indexOf("vec3 CompositeGlow("),
  );
  if (!display || !display.includes("return pow"))
    throw Error("Missing display function");
  const route = JSON.parse(read("packages/blackhole/routes.json"))["/"].idle[0];
  const { right, up } = atlas.camera;
  const vec = (v) => `vec3(${v.map((x) => Number(x).toFixed(10)).join(",")})`;
  const camera = `float bhOne(){return min(iResolution.x,1.0); }\n#define uCameraPosition (${vec(route.position)}*bhOne())\n#define uCameraRight (${vec(right)}*bhOne())\n#define uCameraUp (${vec(up)}*bhOne())\nfloat bhClock(){return iTime;}\n#define iTime (bhClock()*BLACKHOLE_TIME_SCALE)\n`;
  const scene =
    banner +
    local("settings") +
    camera +
    core +
    "vec3 saturate(vec3 x){return clamp(x,vec3(0.0),vec3(1.0));}\n" +
    display +
    local("scene");
  const constants = `const int bhAtlas[${atlas.alpha.length}] = int[${atlas.alpha.length}](${atlas.alpha.join(",")});\nconst int bhMetrics[${atlas.metrics.length}] = int[${atlas.metrics.length}](${atlas.metrics.join(",")});\n`;
  const sampling = `
vec4 bhMetric(int index) { int p=clamp(index,0,uGlyphCount-1)*4;return vec4(bhMetrics[p],bhMetrics[p+1],bhMetrics[p+2],bhMetrics[p+3])/255.0; }
float bhAlpha(int p){ivec2 pixel=ivec2(p%int(iResolution.x),p/int(iResolution.x));return texelFetch(iChannel0,pixel,0).a;}
vec3 bhScenePixel(ivec2 p){ivec2 size=bhSourceSize();p=clamp(p,ivec2(0),size-1);int i=(p.y*size.x+p.x)*3;return vec3(bhAlpha(i),bhAlpha(i+1),bhAlpha(i+2));}
vec4 bhScene(vec2 uv){vec2 p=uv*vec2(bhSourceSize())-0.5;ivec2 base=ivec2(floor(p));vec2 f=fract(p);return vec4(mix(mix(bhScenePixel(base),bhScenePixel(base+ivec2(1,0)),f.x),mix(bhScenePixel(base+ivec2(0,1)),bhScenePixel(base+ivec2(1,1)),f.x),f.y),1.0);}
float bhGlyphPixel(ivec2 p){p=clamp(p,ivec2(0),ivec2(${atlas.width - 1},${atlas.height - 1}));return float(bhAtlas[(${atlas.height - 1}-p.y)*${atlas.width}+p.x])/255.0;}
vec4 bhGlyph(vec2 uv){vec2 p=uv*vec2(${atlas.width}.0,${atlas.height}.0)-0.5;ivec2 b=ivec2(floor(p));vec2 f=fract(p);float a=mix(mix(bhGlyphPixel(b),bhGlyphPixel(b+ivec2(1,0)),f.x),mix(bhGlyphPixel(b+ivec2(0,1)),bhGlyphPixel(b+ivec2(1,1)),f.x),f.y);return vec4(1.0,1.0,1.0,a);}
vec4 cellColor; vec4 cellState;
`;
  let analysis = shader("ascii-analysis").replace(
    /layout\(location=[01]\) out vec4 \w+;/g,
    "",
  );
  analysis = replaceOnce(
    analysis,
    "void main() {",
    "void bhAnalyze(vec2 fragCoord) {",
  );
  analysis = replaceOnce(
    analysis,
    "ivec2 cell = ivec2(gl_FragCoord.xy);",
    "ivec2 cell = ivec2(floor(fragCoord / uAsciiCellSize));",
  );
  analysis = analysis
    .replace(
      /texelFetch\(iChannel2, ivec2\(index, 0\), 0\)/g,
      "bhMetric(index)",
    )
    .replace(/texture\(iChannel0, /g, "bhScene(");
  analysis = replaceOnce(
    analysis,
    "texelFetch(iChannel1, cell, 0)",
    "vec4(0.0)",
  );
  analysis = replaceOnce(analysis, "texelFetch(iChannel3, cell, 0).a", "0.0");
  analysis = replaceOnce(
    analysis,
    "bool history = iFrame > 0",
    "bool history = false",
  );
  let ascii = shader("ascii")
    .replace("void mainImage(", "void bhAscii(")
    .replace("texture(iChannel0, uv)", "bhScene(uv)")
    .replace("texelFetch(uAsciiAnalysisColor, cell, 0)", "cellColor")
    .replace("texelFetch(uAsciiAnalysisState, cell, 0)", "cellState")
    .replace("texture(iChannel1, ", "bhGlyph(")
    .replace("texelFetch(iChannel2, ivec2(index, 0), 0)", "bhMetric(index)");
  const analysisPass =
    banner +
    local("settings") +
    constants +
    sampling +
    analysis +
    local("analysis");
  const unpack = `
void bhReadAnalysis(vec2 fragCoord){ivec2 grid=ivec2(ceil(iResolution.xy/uAsciiCellSize));ivec2 cell=ivec2(floor(fragCoord/uAsciiCellSize));int p=(cell.y*grid.x+cell.x)*8+bhSourceSize().x*bhSourceSize().y*3;cellColor=vec4(bhAlpha(p),bhAlpha(p+1),bhAlpha(p+2),bhAlpha(p+3));cellState=vec4(bhAlpha(p+4),bhAlpha(p+5),bhAlpha(p+6),bhAlpha(p+7));}
`;
  const composite =
    banner +
    local("settings") +
    constants +
    sampling +
    unpack +
    "\nvec3 CompositeGlow(vec3 base,vec2 uv,vec3 sourceColor){return base;}\n" +
    ascii +
    local("composite").replace(
      "bhAnalyze(fragCoord);",
      "bhReadAnalysis(fragCoord);",
    );
  return {
    "blackhole-scene.glsl": scene.replace(/[ \t]+$/gm, ""),
    "blackhole-analysis.glsl": analysisPass.replace(/[ \t]+$/gm, ""),
    "blackhole.glsl": composite.replace(/[ \t]+$/gm, ""),
  };
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  for (const [name, content] of Object.entries(generate())) {
    const target = path.join(root, "integrations/ghostty", name);
    if (check) {
      if (readFileSync(target, "utf8").replace(/\r\n/g, "\n") !== content)
        throw Error(`${name} is stale; regenerate`);
    } else writeFileSync(target, content);
  }
  console.log(
    check
      ? "Ghostty generated shaders match canonical sources."
      : "Generated Ghostty shader chain.",
  );
}
