import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, symlinkSync, readFileSync, existsSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { install, parse } from '../bin/blackhole.mjs';
import native from '../bin/native.cjs';
function fixture(t){const cwd=mkdtempSync(path.join(tmpdir(),'blackhole-test-'));t.after(()=>rmSync(cwd,{recursive:true,force:true}));return cwd;}
test('dry-run does not write; install refuses clobber; overwrite is explicit',t=>{const cwd=fixture(t);const files={'src/a.ts':'hello'};install(files,{outDir:'component',dryRun:true},cwd);assert.equal(existsSync(path.join(cwd,'component')),false);install(files,{outDir:'component'},cwd);assert.throws(()=>install({'src/a.ts':'changed'},{outDir:'component'},cwd),/overwrite/);assert.equal(readFileSync(path.join(cwd,'component/src/a.ts'),'utf8'),'hello');install({'src/a.ts':'changed'},{outDir:'component',overwrite:true},cwd);assert.equal(readFileSync(path.join(cwd,'component/src/a.ts'),'utf8'),'changed');});
test('rejects traversal, escaping absolute paths, destination symlinks and bundled traversal',t=>{const cwd=fixture(t);for(const outDir of ['../escape','a/../../escape','/tmp/escape'])assert.throws(()=>install({'a':'x'},{outDir},cwd));mkdirSync(path.join(cwd,'real'));symlinkSync(path.join(cwd,'real'),path.join(cwd,'link'));assert.throws(()=>install({'a':'x'},{outDir:'link',overwrite:true},cwd),/Symlink/);symlinkSync(path.join(cwd,'target'),path.join(cwd,'real','a'));assert.throws(()=>install({'a':'x'},{outDir:'real',overwrite:true},cwd),/Symlink/);assert.throws(()=>install({'../a':'x'},{outDir:'component'},cwd),/Invalid/);});
test('preflight rejects entire write before partial install',t=>{const cwd=fixture(t);mkdirSync(path.join(cwd,'component'));writeFileSync(path.join(cwd,'component/b'),'existing');assert.throws(()=>install({a:'new',b:'changed'},{outDir:'component'},cwd));assert.equal(existsSync(path.join(cwd,'component/a')),false);});
test('strict parser forwards explorer args and rejects malformed options',()=>{assert.deepEqual(parse(['explore','--version']).args,['--version']);assert.throws(()=>parse(['add','--wat']),/Unknown/);assert.throws(()=>parse(['add','--out-dir']),/Missing/);});
test('launcher resolves exact platform package and rejects unsupported targets',()=>{const calls=[];const resolve=(name)=>{calls.push(name);return '/native/blackhole';};assert.equal(native.executable('darwin','arm64','/root',resolve),'/native/blackhole');assert.deepEqual(calls,['@austindelic/blackhole-darwin-arm64/bin/blackhole']);assert.throws(()=>native.executable('linux','ia32'),/Unsupported/);assert.throws(()=>native.executable('win32','x64','/root',()=>{const e=new Error();e.code='MODULE_NOT_FOUND';throw e;}),/no runtime download/);});
test('npm-style bin symlink executes the CLI',async t=>{const {execFileSync}=await import('node:child_process');const cwd=fixture(t);const link=path.join(cwd,'blackhole');symlinkSync(new URL('../bin/blackhole.mjs',import.meta.url),link);assert.equal(execFileSync(process.execPath,[link,'--version'],{encoding:'utf8'}).trim(),'0.1.1');});
test('template contains complete editable source and binary fonts',t=>{const cwd=fixture(t);const files=JSON.parse(readFileSync(new URL('../templates/source.json',import.meta.url),'utf8'));delete files['src/react.tsx'];install(files,{outDir:'source'},cwd);assert.equal(readFileSync(path.join(cwd,'source/fonts/DepartureMono-Regular.woff2')).subarray(0,4).toString(),'wOF2');assert.ok(files['src/types/webgpu.d.ts']);assert.equal(readFileSync(path.join(cwd,'source/tooling/webgpu/port-shaders.mjs'),'utf8'),readFileSync(new URL('../../blackhole/tooling/webgpu/port-shaders.mjs',import.meta.url),'utf8'));assert.match(files['README.md'],/cargo install naga-cli --version 27\.0\.0 --locked/);assert.doesNotMatch(files['src/components/BlackHoleWebGpuBackend.ts'],/reference types="@webgpu/);});
test('editing copied canonical shader regenerates the embedded source',async t=>{const {execFileSync}=await import('node:child_process');const cwd=fixture(t);const files=JSON.parse(readFileSync(new URL('../templates/source.json',import.meta.url),'utf8'));install(files,{outDir:'source'},cwd);const root=path.join(cwd,'source');const shader=path.join(root,'shaders/image.glsl');writeFileSync(shader,readFileSync(shader,'utf8')+'\n// source-edit-check\n');execFileSync(process.execPath,['scripts/embed.mjs'],{cwd:root});assert.match(readFileSync(path.join(root,'src/embedded/shaders_image.glsl.ts'),'utf8'),/source-edit-check/);assert.equal(readFileSync(path.join(root,'fonts/DepartureMono-Regular.woff2')).subarray(0,4).toString(),'wOF2');});
